auto: true
server: true
permalink: none
baseurl: "/geografisch"
exclude:
- .gitignore
- README.md

BASE_PATH: "http://127.0.0.1:4000/geografisch/"
STATIC_URL: "/geografisch/static"

navigation:
- text: Home
  url: home
- text: Portfolio
  url: portfolio
- text: Blog
  url: blog
- text: Contact
  url: contact


prose:
  rooturl: "_posts"
  metadata: 
    _posts/articles: |
      published: true
      layout: article
      title: Prose test
      abstract: Short summary of your article.
      author_twitter: geo_grafisch
      author: Marc Beringen
      categories:
      - articles