auto: true
server: true
permalink: none
baseurl: ""
exclude:
- .gitignore
- README.md

navigation:
- text: Home
  url: /index.html
- text: Portfolio
  url: /portfolio/
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Contact
  url: /contact/


prose:
  rooturl: "_posts"
  metadata: 
    _posts/articles: |
      published: true
      layout: article
      title: Prose test
      abstract: Short summary of your article.
      author_twitter: geo_grafisch
      author: Marc Beringen
      categories:
      - articles